apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-stack-prod
  labels:
    app: time-stack-chain
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    matchLabels:
      app: time-stack-chain
  template:
    metadata:
      labels:
        app: time-stack-chain
    spec:
      containers:
      - name: time-stack-chain
        image: muhammadyasser/ruby-udacity:latest
        ports:
        - containerPort: 3000
---

kind: Service
apiVersion: v1
metadata:
  name: time-stack-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  selector:
    app: time-stack-chain
  type: LoadBalancer
