defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: admin 
  password: rsi11112222
  pool: 5
  host: udacity-1.coa3nv0zxmy6.us-west-2.rds.amazonaws.com
  

### ALTER USER 'yasser'@'%' IDENTIFIED WITH mysql_native_password BY 'rsi1111'; 
test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: development

cucumber:
  <<: *test

production:
  <<: *defaults
  database: <%= ENV['DATABASE'] %> 
